services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=password'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=open_courseware'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=courseware'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=courseware'
    ports:
      - '5672:5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
