INSERT INTO department (title)
VALUES ('Aeronautics and Astronautics'),
       ('Anthropology'),
       ('Architecture'),
       ('Biological Engineering'),
       ('Biology'),
       ('Brain and Cognitive Sciences'),
       ('Chemical Engineering'),
       ('Chemistry'),
       ('Civil and Environmental Engineering'),
       ('Comparative Media Studies/Writing'),
       ('Earth, Atmospheric, and Planetary Sciences'),
       ('Economics'),
       ('Electrical Engineering and Computer Science'),
       ('Engineering Systems Division'),
       ('Global Languages'),
       ('Health Sciences and Technology'),
       ('History'),
       ('Linguistics and Philosophy'),
       ('Literature'),
       ('Materials Science and Engineering'),
       ('Mathematics'),
       ('Mechanical Engineering'),
       ('Media Arts and Sciences'),
       ('Music and Theater Arts'),
       ('Nuclear Science and Engineering'),
       ('Physics'),
       ('Political Science'),
       ('Science, Technology, and Society'),
       ('Urban Studies and Planning');