INSERT INTO topic (id, title, main_topic_id, created_at, updated_at, type, dtype)
VALUES (1, 'Science', NULL, NOW(), NOW(), 'MAIN', 0),
       (2, 'Technology', NULL, NOW(), NOW(), 'MAIN', 0),
       (3, 'Engineering', NULL, NOW(), NOW(), 'MAIN', 0),
       (4, 'Mathematics', NULL, NOW(), NOW(), 'MAIN', 0),
       (5, 'Arts', NULL, NOW(), NOW(), 'MAIN', 0),
       (6, 'Social Sciences', NULL, NOW(), NOW(), 'MAIN', 0),
       (7, 'History', NULL, NOW(), NOW(), 'MAIN', 0),
       (8, 'Language and Literature', NULL, NOW(), NOW(), 'MAIN', 0),
       (9, 'Biology', 1, NOW(), NOW(), 'SUB', 1),
       (10, 'Chemistry', 1, NOW(), NOW(), 'SUB', 1),
       (11, 'Physics', 1, NOW(), NOW(), 'SUB', 1),
       (12, 'Astronomy', 1, NOW(), NOW(), 'SUB', 1),
       (13, 'Computer Science', 2, NOW(), NOW(), 'SUB', 1),
       (14, 'Information Technology', 2, NOW(), NOW(), 'SUB', 1),
       (15, 'Software Engineering', 2, NOW(), NOW(), 'SUB', 1),
       (16, 'Electrical Engineering', 3, NOW(), NOW(), 'SUB', 1),
       (17, 'Mechanical Engineering', 3, NOW(), NOW(), 'SUB', 1),
       (18, 'Civil Engineering', 3, NOW(), NOW(), 'SUB', 1),
       (19, 'Industrial Engineering', 3, NOW(), NOW(), 'SUB', 1),
       (20, 'Chemical Engineering', 3, NOW(), NOW(), 'SUB', 1),
       (21, 'Algebra', 4, NOW(), NOW(), 'SUB', 1),
       (22, 'Calculus', 4, NOW(), NOW(), 'SUB', 1),
       (23, 'Geometry', 4, NOW(), NOW(), 'SUB', 1),
       (24, 'Statistics', 4, NOW(), NOW(), 'SUB', 1),
       (25, 'Discrete Mathematics', 4, NOW(), NOW(), 'SUB', 1),
       (26, 'Visual Arts', 5, NOW(), NOW(), 'SUB', 1),
       (27, 'Performing Arts', 5, NOW(), NOW(), 'SUB', 1),
       (28, 'Literature', 8, NOW(), NOW(), 'SUB', 1),
       (29, 'Linguistics', 8, NOW(), NOW(), 'SUB', 1),
       (30, 'Poetry', 8, NOW(), NOW(), 'SUB', 1),
       (31, 'Fiction', 8, NOW(), NOW(), 'SUB', 1),
       (32, 'Non-Fiction', 8, NOW(), NOW(), 'SUB', 1),
       (33, 'Psychology', 6, NOW(), NOW(), 'SUB', 1),
       (34, 'Sociology', 6, NOW(), NOW(), 'SUB', 1),
       (35, 'Anthropology', 6, NOW(), NOW(), 'SUB', 1),
       (36, 'Economics', 6, NOW(), NOW(), 'SUB', 1),
       (37, 'Political Science', 6, NOW(), NOW(), 'SUB', 1),
       (38, 'Geography', 6, NOW(), NOW(), 'SUB', 1),
       (39, 'World History', 7, NOW(), NOW(), 'SUB', 1),
       (40, 'European History', 7, NOW(), NOW(), 'SUB', 1),
       (41, 'American History', 7, NOW(), NOW(), 'SUB', 1),
       (42, 'Asian History', 7, NOW(), NOW(), 'SUB', 1),
       (43, 'African History', 7, NOW(), NOW(), 'SUB', 1),
       (44, 'Latin American History', 7, NOW(), NOW(), 'SUB', 1),
       (45, 'English Language', 8, NOW(), NOW(), 'SUB', 1),
       (46, 'French Language', 8, NOW(), NOW(), 'SUB', 1),
       (47, 'Spanish Language', 8, NOW(), NOW(), 'SUB', 1),
       (48, 'German Language', 8, NOW(), NOW(), 'SUB', 1),
       (49, 'Chinese Language', 8, NOW(), NOW(), 'SUB', 1);
